//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: _LPT_m_hActorList_16.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class _LPT_m_hActorList_16
	{
	public:
		int    	lengthprop16; // 0x0
	};
#pragma pack(pop)
