//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: _LPT_m_AnimOverlay_15.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class _LPT_m_AnimOverlay_15
	{
	public:
		int    	lengthprop15; // 0x0
	};
#pragma pack(pop)
