//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: _ST_m_AnimOverlay_15.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class _ST_m_AnimOverlay_15
	{
	public:
		int    	lengthprop15; // 0x0
		float  	m_flPrevCycle; // 0x4
		float  	m_flWeight; // 0x8
		int    	m_nOrder; // 0xc
		unsigned char _0x10[0x4];
		float  	m_flCycle; // 0x14
	};
#pragma pack(pop)
