//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: _ST_m_hActorList_16.h
//***********************************************

#pragma once

#include "_LPT_m_hActorList_16.h"

#pragma pack(push,1)
	class _ST_m_hActorList_16
	{
	public:
		_LPT_m_hActorList_16	lengthproxy; // 0x0
	};
#pragma pack(pop)
