//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CAI_BaseNPC.h
//***********************************************

#pragma once

#include "CBaseCombatCharacter.h"

#pragma pack(push,1)
	class CAI_BaseNPC : 
		 public CBaseCombatCharacter // 0x220c
	{
	public:
		int    	m_lifeState; // 0x8f
		unsigned char _0x93[0x217d];
		float  	m_flTimePingEffect; // 0x2210
		int    	m_iDeathPose; // 0x2214
		int    	m_iDeathFrame; // 0x2218
		int    	m_iSpeedModRadius; // 0x221c
		int    	m_iSpeedModSpeed; // 0x2220
		int    	m_bPerformAvoidance; // 0x2224
		int    	m_bIsMoving; // 0x2225
		int    	m_bFadeCorpse; // 0x2226
		int    	m_bSpeedModActive; // 0x2227
		int    	m_bImportanRagdoll; // 0x2228
	};
#pragma pack(pop)
