//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CAlyxEmpEffect.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CAlyxEmpEffect : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_nState; // 0x1388
		float  	m_flDuration; // 0x138c
		float  	m_flStartTime; // 0x1390
	};
#pragma pack(pop)
