//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CAnimTimeMustBeFirst.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CAnimTimeMustBeFirst
	{
	public:
		unsigned char _0x0[0x60];
		int    	m_flAnimTime; // 0x60
	};
#pragma pack(pop)
