//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CAnimationlayer.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CAnimationlayer
	{
	public:
		int    	m_nSequence; // 0x0
		float  	m_flPrevCycle; // 0x4
		float  	m_flWeight; // 0x8
		int    	m_nOrder; // 0xc
		unsigned char _0x10[0x4];
		float  	m_flCycle; // 0x14
	};
#pragma pack(pop)
