//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CAR2Explosion.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CAR2Explosion : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x147c];
		char*  	m_szMaterialName; // 0x147c
	};
#pragma pack(pop)
