//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBarnacle.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CBarnacle : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x10];
		vector3	m_vecRoot; // 0x223c
		vector3	m_vecTip; // 0x2248
		vector3	m_vecTipDrawOffset; // 0x2254
		float  	m_flAltitude; // 0x2260
	};
#pragma pack(pop)
