//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseAnimating.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CBaseAnimating : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x50];
		int    	m_nSkin; // 0x1390
		int    	m_nBody; // 0x1394
		int    	m_nHitboxSet; // 0x1398
		unsigned char _0x139c[0x1c];
		float  	m_flPlaybackRate; // 0x13b8
		unsigned char _0x13bc[0x8];
		vector3	m_vecForce; // 0x13c4
		int    	m_nForceBone; // 0x13d0
		unsigned char _0x13d4[0x2c];
		int    	m_bClientSideFrameReset; // 0x1400
		unsigned char _0x1404[0x34];
		float  	m_fadeMinDist; // 0x1438
		float  	m_fadeMaxDist; // 0x143c
		float  	m_flFadeScale; // 0x1440
		unsigned char _0x1444[0x4c];
		float  	m_flModelScale; // 0x1490
		int    	m_flPoseParameter[24]; // 0x1494
		unsigned char _0x14f4[0xbc];
		int    	m_flEncodedController[4]; // 0x15b0
		unsigned char _0x15c0[0x40];
		int    	m_bClientSideAnimation; // 0x1600
		int    	m_nNewSequenceParity; // 0x1604
		int    	m_nResetEventsParity; // 0x1608
		unsigned char _0x160c[0x24];
		int    	m_nSequence; // 0x1630
		unsigned char _0x1634[0x4];
		float  	m_flCycle; // 0x1638
		unsigned char _0x163c[0x7c];
		int    	m_hLightingOrigin; // 0x16b8
		int    	m_hLightingOriginRelative; // 0x16bc
		int    	m_nMuzzleFlashParity; // 0x16c0
		unsigned char _0x16c4[0x1c];
		vector3	m_OverrideViewTarget; // 0x16e0
		unsigned char _0x16ec[0x80];
		int    	m_pBoneManipulator; // 0x176c
		unsigned char _0x1770[0x4];
		int    	m_pFlexManipulator; // 0x1774
	};
#pragma pack(pop)
