//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseHL2MPBludgeonWeapon.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CBaseHL2MPBludgeonWeapon : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
	};
#pragma pack(pop)
