//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseHL1MPCombatWeapon.h
//***********************************************

#pragma once

#include "CBaseHL1CombatWeapon.h"

#pragma pack(push,1)
	class CBaseHL1MPCombatWeapon : 
		 public CBaseHL1CombatWeapon // 0x0
	{
	public:
	};
#pragma pack(pop)
