//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseFlex.h
//***********************************************

#pragma once

#include "CBaseAnimatingOverlay.h"

#pragma pack(push,1)
	class CBaseFlex : 
		 public CBaseAnimatingOverlay // 0x18
	{
	public:
		unsigned char _0x18[0xd0];
		float  	m_vecViewOffset_0; // 0xe8
		float  	m_vecViewOffset_1; // 0xec
		float  	m_vecViewOffset_2; // 0xf0
		unsigned char _0xf4[0x1738];
		vector3	m_viewtarget; // 0x182c
		unsigned char _0x1838[0x30];
		int    	m_flexWeight[96]; // 0x1868
		unsigned char _0x19e8[0x30];
		int    	m_blinktoggle; // 0x1a18
		unsigned char _0x1a1c[0x168];
		vector3	m_vecLean; // 0x1b84
		unsigned char _0x1b90[0x30];
		vector3	m_vecShift; // 0x1bc0
	};
#pragma pack(pop)
