//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseCombatCharacter.h
//***********************************************

#pragma once

#include "CBaseFlex.h"
#include "CBCCLocalPlayerExclusive.h"

#pragma pack(push,1)
	class CBaseCombatCharacter : 
		 public CBaseFlex // 0x1bcc
	{
	public:
		CBCCLocalPlayerExclusive	bcc_localdata; // 0x0
		int    	m_bloodColor; // 0x1c04
		unsigned char _0x1c08[0x200];
		int    	m_hMyWeapons[256]; // 0x1e08
		int    	m_hActiveWeapon; // 0x2208
	};
#pragma pack(pop)
