//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseGrenade.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CBaseGrenade : 
		 public CBaseAnimating // 0x1778
	{
	public:
		vector3	m_vecVelocity; // 0xf4
		unsigned char _0x100[0x250];
		int    	m_fFlags; // 0x350
		unsigned char _0x354[0x146d];
		int    	m_bIsLive; // 0x17c1
		float  	m_DmgRadius; // 0x17c4
		unsigned char _0x17c8[0xc];
		float  	m_flDamage; // 0x17d4
		unsigned char _0x17d8[0x4];
		int    	m_hThrower; // 0x17dc
	};
#pragma pack(pop)
