//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseTempEntity.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CBaseTempEntity
	{
	public:
	};
#pragma pack(pop)
