//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBasePropDoor.h
//***********************************************

#pragma once

#include "CDynamicProp.h"

#pragma pack(push,1)
	class CBasePropDoor : 
		 public CDynamicProp // 0x17c4
	{
	public:
	};
#pragma pack(pop)
