//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBasePlayer.h
//***********************************************

#pragma once

#include "CBaseCombatCharacter.h"
#include "CLocal.h"
#include "CPlayerState.h"

#pragma pack(push,1)
	class CBasePlayer : 
		 public CBaseCombatCharacter // 0x220c
	{
	public:
		int    	m_nNextThinkTick; // 0x84
		unsigned char _0x88[0x7];
		int    	m_lifeState; // 0x8f
		int    	m_iHealth; // 0x90
		unsigned char _0x94[0x54];
		float  	m_vecViewOffset_0; // 0xe8
		float  	m_vecViewOffset_1; // 0xec
		float  	m_vecViewOffset_2; // 0xf0
		float  	m_vecVelocity_0; // 0xf4
		float  	m_vecVelocity_1; // 0xf8
		float  	m_vecVelocity_2; // 0xfc
		unsigned char _0x100[0x58];
		vector3	m_vecBaseVelocity; // 0x158
		unsigned char _0x164[0xf0];
		int    	m_hGroundEntity; // 0x254
		unsigned char _0x258[0x4];
		float  	m_flFriction; // 0x25c
		unsigned char _0x260[0xf0];
		int    	m_fFlags; // 0x350
		unsigned char _0x354[0x18b4];
		int    	m_iAmmo[128]; // 0x1c08
		unsigned char _0x1e08[0x454];
		CLocal	m_Local; // 0x225c
		CPlayerState	pl; // 0x2454
		unsigned char _0x245c[0xc];
		float  	m_iFOV; // 0x2468
		float  	m_iFOVStart; // 0x246c
		float  	m_flFOVTime; // 0x2470
		float  	m_iDefaultFOV; // 0x2474
		int    	m_hZoomOwner; // 0x2478
		int    	m_fOnTarget; // 0x247c
		unsigned char _0x2480[0x34];
		int    	m_hConstraintEntity; // 0x24b4
		vector3	m_vecConstraintCenter; // 0x24b8
		float  	m_flConstraintRadius; // 0x24c4
		float  	m_flConstraintWidth; // 0x24c8
		float  	m_flConstraintSpeedFactor; // 0x24cc
		int    	m_iObserverMode; // 0x24d0
		int    	m_hObserverTarget; // 0x24d4
		unsigned char _0x24d8[0x1c];
		float  	m_flDeathTime; // 0x24f4
		unsigned char _0x24f8[0x8];
		int    	m_hVehicle; // 0x2500
		unsigned char _0x2504[0x4];
		int    	m_hUseEntity; // 0x2508
		float  	m_flMaxspeed; // 0x250c
		int    	m_iBonusProgress; // 0x2510
		int    	m_iBonusChallenge; // 0x2514
		unsigned char _0x2518[0x68];
		int    	m_nTickBase; // 0x2580
		unsigned char _0x2584[0xe];
		int    	m_bUseWeaponsInVehicle; // 0x2592
		unsigned char _0x2596[0x2];
		int    	m_hLastWeapon; // 0x2598
		unsigned char _0x259c[0x14];
		int    	m_hViewModel_0; // 0x25b0
		unsigned char _0x25b4[0x3a8];
		float  	m_flLaggedMovementValue; // 0x295c
		unsigned char _0x2960[0x1c];
		char*  	m_szLastPlaceName; // 0x297c
		unsigned char _0x2980[0x1ac];
		int    	m_hViewEntity; // 0x2b2c
	};
#pragma pack(pop)
