//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseHL2MPCombatWeapon.h
//***********************************************

#pragma once

#include "CWeaponHL2MPBase.h"

#pragma pack(push,1)
	class CBaseHL2MPCombatWeapon : 
		 public CWeaponHL2MPBase // 0x0
	{
	public:
	};
#pragma pack(pop)
