//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBaseHelicopter.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CBaseHelicopter : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x4];
		float  	m_flStartupTime; // 0x2230
	};
#pragma pack(pop)
