//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBCCLocalPlayerExclusive.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CBCCLocalPlayerExclusive
	{
	public:
		unsigned char _0x0[0x1c00];
		float  	m_flNextAttack; // 0x1c00
	};
#pragma pack(pop)
