//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBoneFollower.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CBoneFollower : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_modelIndex; // 0x1388
		int    	m_solidIndex; // 0x138c
	};
#pragma pack(pop)
