//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CBoneManipulate.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CBoneManipulate : 
		 public CBaseEntity // 0x1340
	{
	public:
		bool   	m_BonePos[1]; // 0x0
		unsigned char _0x0[0x1388];
		vector3	m_BonePos_0; // 0x1388
		unsigned char _0x1394[0xbf4];
		vector3	m_BoneScale_0; // 0x1f88
		unsigned char _0x1f94[0xbf4];
		vector3	m_BoneAng_0; // 0x2b88
		unsigned char _0x2b94[0xbf4];
		int    	m_BoneJiggle_0; // 0x3788
	};
#pragma pack(pop)
