//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CCitadelEnergyCore.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CCitadelEnergyCore : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flScale; // 0x1388
		int    	m_nState; // 0x138c
		float  	m_flDuration; // 0x1390
		float  	m_flStartTime; // 0x1394
		int    	m_spawnflags; // 0x1398
	};
#pragma pack(pop)
