//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CColorCorrectionVolume.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CColorCorrectionVolume : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_Weight; // 0x1388
		char*  	m_lookupFilename; // 0x138c
	};
#pragma pack(pop)
