//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CColorCorrection.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CColorCorrection : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		vector3	m_vecOrigin; // 0x1388
		float  	m_minFalloff; // 0x1394
		float  	m_maxFalloff; // 0x1398
		float  	m_flCurWeight; // 0x139c
		char*  	m_netLookupFilename; // 0x13a0
		unsigned char _0x13a4[0x100];
		int    	m_bEnabled; // 0x14a4
	};
#pragma pack(pop)
