//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CCombineGunship.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CCombineGunship
	{
	public:
		unsigned char _0x0[0x2280];
		vector3	m_vecHitPos; // 0x2280
	};
#pragma pack(pop)
