//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CCorpse.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CCorpse : 
		 public CBaseAnimating // 0x1778
	{
	public:
		unsigned char _0x1778[0x48];
		int    	m_nReferencePlayer; // 0x17c0
	};
#pragma pack(pop)
