//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CCPropJeepEpisodic.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CCPropJeepEpisodic
	{
	public:
		bool   	m_vecRadarContactPos[1]; // 0x0
		unsigned char _0x0[0x1910];
		int    	m_iNumRadarContacts; // 0x1910
		vector3	m_vecRadarContactPos_0; // 0x1914
		unsigned char _0x1920[0x114];
		int    	m_iRadarContactType_0; // 0x1a34
	};
#pragma pack(pop)
