//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CCrossbowBolt.h
//***********************************************

#pragma once

#include "CBaseCombatCharacter.h"

#pragma pack(push,1)
	class CCrossbowBolt : 
		 public CBaseCombatCharacter // 0x220c
	{
	public:
	};
#pragma pack(pop)
