//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CDetailController.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CDetailController
	{
	public:
		unsigned char _0x0[0x1388];
		float  	m_flFadeStartDist; // 0x1388
		float  	m_flFadeEndDist; // 0x138c
	};
#pragma pack(pop)
