//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CDustTrail.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CDustTrail : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1474];
		float  	m_SpawnRate; // 0x1474
		vector3	m_Color; // 0x1478
		float  	m_Opacity; // 0x1484
		float  	m_ParticleLifetime; // 0x1488
		unsigned char _0x148c[0x4];
		float  	m_StopEmitTime; // 0x1490
		float  	m_MinSpeed; // 0x1494
		float  	m_MaxSpeed; // 0x1498
		float  	m_MinDirectedSpeed; // 0x149c
		float  	m_MaxDirectedSpeed; // 0x14a0
		float  	m_StartSize; // 0x14a4
		float  	m_EndSize; // 0x14a8
		float  	m_SpawnRadius; // 0x14ac
		unsigned char _0x14b0[0xc];
		int    	m_bEmit; // 0x14bc
	};
#pragma pack(pop)
