//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CDynamicLight.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CDynamicLight : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_Flags; // 0x1388
		int    	m_LightStyle; // 0x1389
		float  	m_Radius; // 0x138c
		int    	m_Exponent; // 0x1390
		float  	m_InnerAngle; // 0x1394
		float  	m_OuterAngle; // 0x1398
		float  	m_SpotRadius; // 0x139c
	};
#pragma pack(pop)
