//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CDynamicProp.h
//***********************************************

#pragma once

#include "CBreakableProp.h"

#pragma pack(push,1)
	class CDynamicProp : 
		 public CBreakableProp // 0x0
	{
	public:
		unsigned char _0x0[0x17c0];
		int    	m_bUseHitboxesForRenderBox; // 0x17c0
	};
#pragma pack(pop)
