//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEmbers.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CEmbers : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_nDensity; // 0x1388
		int    	m_nLifetime; // 0x138c
		int    	m_nSpeed; // 0x1390
		int    	m_bEmit; // 0x1394
	};
#pragma pack(pop)
