//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEntityParticleTrail.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"
#include "CEntityParticleTrailInfo.h"

#pragma pack(push,1)
	class CEntityParticleTrail : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1470];
		int    	m_iMaterialName; // 0x1470
		CEntityParticleTrailInfo	m_Info; // 0x1474
		int    	m_hConstraintEntity; // 0x1488
	};
#pragma pack(pop)
