//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEntityParticleTrailInfo.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CEntityParticleTrailInfo
	{
	public:
		unsigned char _0x0[0x8];
		float  	m_flLifetime; // 0x8
		float  	m_flStartSize; // 0xc
		float  	m_flEndSize; // 0x10
	};
#pragma pack(pop)
