//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEntityFlame.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CEntityFlame : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x4c];
		int    	m_hEntAttached; // 0x138c
	};
#pragma pack(pop)
