//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEnvScreenEffect.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CEnvScreenEffect : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flDuration; // 0x1388
		int    	m_nType; // 0x138c
	};
#pragma pack(pop)
