//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEnvScreenOverlay.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CEnvScreenOverlay : 
		 public CBaseEntity // 0x1340
	{
	public:
		bool   	m_iszOverlayNames[1]; // 0x0
		unsigned char _0x0[0x1388];
		char*  	m_iszOverlayNames_0; // 0x1388
		unsigned char _0x138c[0x9f4];
		float  	m_flOverlayTimes_0; // 0x1d80
		unsigned char _0x1d84[0x24];
		float  	m_flStartTime; // 0x1da8
		int    	m_iDesiredOverlay; // 0x1dac
		int    	m_bIsActive; // 0x1db0
	};
#pragma pack(pop)
