//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEnvStarfield.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CEnvStarfield : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x4c];
		int    	m_bOn; // 0x138c
		float  	m_flDensity; // 0x1390
	};
#pragma pack(pop)
