//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEnvWind.h
//***********************************************

#pragma once

#include "CBaseEntity.h"
#include "CEnvWindShared.h"

#pragma pack(push,1)
	class CEnvWind : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		CEnvWindShared	m_EnvWindShared; // 0x1388
	};
#pragma pack(pop)
