//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEnvParticleScript.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CEnvParticleScript : 
		 public CBaseAnimating // 0x1778
	{
	public:
		unsigned char _0x1778[0x12c];
		float  	m_flSequenceScale; // 0x18a4
	};
#pragma pack(pop)
