//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CEnvHeadcrabCanister.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"
#include "CEnvHeadcrabCanisterShared.h"

#pragma pack(push,1)
	class CEnvHeadcrabCanister : 
		 public CBaseAnimating // 0x1778
	{
	public:
		unsigned char _0x1778[0x48];
		CEnvHeadcrabCanisterShared	m_Shared; // 0x17c0
		unsigned char _0x1834[0x4];
		int    	m_bLanded; // 0x1838
	};
#pragma pack(pop)
