//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFireTrail.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CFireTrail : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1474];
		int    	m_nAttachment; // 0x1474
		float  	m_flLifetime; // 0x1478
	};
#pragma pack(pop)
