//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFireSmoke.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFireSmoke : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flStartScale; // 0x1388
		float  	m_flScale; // 0x138c
		float  	m_flScaleTime; // 0x1390
		int    	m_nFlags; // 0x1394
		int    	m_nFlameModelIndex; // 0x1398
		int    	m_nFlameFromAboveModelIndex; // 0x139c
	};
#pragma pack(pop)
