//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFlare.h
//***********************************************

#pragma once

#include "CBaseCombatCharacter.h"

#pragma pack(push,1)
	class CFlare : 
		 public CBaseCombatCharacter // 0x220c
	{
	public:
		unsigned char _0x220c[0x108];
		float  	m_flTimeBurnOut; // 0x2314
		float  	m_flScale; // 0x2318
		int    	m_bLight; // 0x231c
		int    	m_bSmoke; // 0x231d
		int    	m_bPropFlare; // 0x231e
	};
#pragma pack(pop)
