//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFleshEffectTarget.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFleshEffectTarget : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flRadius; // 0x1388
		unsigned char _0x138c[0x8];
		float  	m_flScaleTime; // 0x1394
	};
#pragma pack(pop)
