//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFlexManipulate.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFlexManipulate : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_iFlexWeights[96]; // 0x1388
		float  	m_flexScale; // 0x1508
		vector3	m_EyesLocalTarget; // 0x150c
	};
#pragma pack(pop)
