//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFuncAreaPortalWindow.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFuncAreaPortalWindow : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flFadeStartDist; // 0x1388
		float  	m_flFadeDist; // 0x138c
		float  	m_flTranslucencyLimit; // 0x1390
		int    	m_iBackgroundModelIndex; // 0x1394
	};
#pragma pack(pop)
