//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFuncOccluder.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFuncOccluder : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_nOccluderIndex; // 0x1388
		int    	m_bActive; // 0x138c
	};
#pragma pack(pop)
