//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFuncSmokeVolume.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"
#include "CCollisionProperty.h"

#pragma pack(push,1)
	class CFuncSmokeVolume : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x19c];
		CCollisionProperty	m_Collision; // 0x19c
		unsigned char _0x210[0x1264];
		int    	m_Color1; // 0x1474
		int    	m_Color2; // 0x1478
		char*  	m_MaterialName; // 0x147c
		unsigned char _0x1480[0xfc];
		float  	m_ParticleDrawWidth; // 0x157c
		float  	m_ParticleSpacingDistance; // 0x1580
		float  	m_DensityRampSpeed; // 0x1584
		float  	m_RotationSpeed; // 0x1588
		float  	m_MovementSpeed; // 0x158c
		float  	m_Density; // 0x1590
		int    	m_spawnflags; // 0x1594
	};
#pragma pack(pop)
