//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFuncRotating.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFuncRotating : 
		 public CBaseEntity // 0x1340
	{
	public:
		int    	m_flSimulationTime; // 0x68
		unsigned char _0x6c[0x2cc];
		vector3	m_vecOrigin; // 0x338
		float  	m_angRotation_0; // 0x344
		float  	m_angRotation_1; // 0x348
		float  	m_angRotation_2; // 0x34c
	};
#pragma pack(pop)
