//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFuncLadder.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFuncLadder : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		vector3	m_vecLadderDir; // 0x1388
		unsigned char _0x1394[0x14];
		vector3	m_vecPlayerMountPositionTop; // 0x13a8
		vector3	m_vecPlayerMountPositionBottom; // 0x13b4
		unsigned char _0x13c0[0x1];
		int    	m_bFakeLadder; // 0x13c1
	};
#pragma pack(pop)
