//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CFuncMonitor.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CFuncMonitor : 
		 public CBaseEntity // 0x1340
	{
	public:
	};
#pragma pack(pop)
