//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CGameRulesProxy.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CGameRulesProxy
	{
	public:
	};
#pragma pack(pop)
