//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CGMODRules.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CGMODRules
	{
	public:
		unsigned char _0x0[0x48];
		float  	m_fTimeScale; // 0x48
		int    	m_iSkillLevel; // 0x4c
		int    	m_bHL2EpisodicBehaviour; // 0x50
	};
#pragma pack(pop)
