//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CGMODGameRulesProxy.h
//***********************************************

#pragma once

#include "CGameRulesProxy.h"
#include "CGMODRules.h"

#pragma pack(push,1)
	class CGMODGameRulesProxy : 
		 public CGameRulesProxy // 0x0
	{
	public:
		CGMODRules	gmod_gamerules_data; // 0x0
	};
#pragma pack(pop)
