//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHandleTest.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CHandleTest : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_Handle; // 0x1388
		int    	m_bSendHandle; // 0x138c
	};
#pragma pack(pop)
