//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHL2MPGameRulesProxy.h
//***********************************************

#pragma once

#include "CHL2MPRules.h"

#pragma pack(push,1)
	class CHL2MPGameRulesProxy
	{
	public:
		CHL2MPRules	hl2mp_gamerules_data; // 0x0
	};
#pragma pack(pop)
