//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHL2MPRagdoll.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CHL2MPRagdoll
	{
	public:
		unsigned char _0x0[0x8c];
		int    	m_nModelIndex; // 0x8c
		unsigned char _0x90[0x1334];
		vector3	m_vecForce; // 0x13c4
		int    	m_nForceBone; // 0x13d0
		unsigned char _0x13d4[0x454];
		int    	m_hPlayer; // 0x1828
		vector3	m_vecRagdollVelocity; // 0x182c
		vector3	m_vecRagdollOrigin; // 0x1838
	};
#pragma pack(pop)
