//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHL2MPMachineGun.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CHL2MPMachineGun : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x1898];
		int    	m_nShotsFired; // 0x1898
	};
#pragma pack(pop)
