//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHL2MPLocalPlayerExclusive.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CHL2MPLocalPlayerExclusive
	{
	public:
		unsigned char _0x0[0x338];
		vector3	m_vecOrigin; // 0x338
		unsigned char _0x344[0x2898];
		float  	m_angEyeAngles_0; // 0x2bdc
		float  	m_angEyeAngles_1; // 0x2be0
	};
#pragma pack(pop)
