//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHL2MP_Player.h
//***********************************************

#pragma once

#include "CHL2_Player.h"

#pragma pack(push,1)
	class CHL2MP_Player : 
		 public CHL2_Player // 0x2bbc
	{
	public:
		vector3	m_vecOrigin; // 0x338
		unsigned char _0x344[0x2898];
		float  	m_angEyeAngles_0; // 0x2bdc
		float  	m_angEyeAngles_1; // 0x2be0
		unsigned char _0x2be4[0x34];
		int    	m_hRagdoll; // 0x2c18
		unsigned char _0x2c1c[0x40];
		int    	m_iSpawnInterpCounter; // 0x2c5c
		unsigned char _0x2c60[0x4];
		int    	m_iPlayerSoundType; // 0x2c64
		unsigned char _0x2c68[0xc];
		int    	m_fIsWalking; // 0x2c74
	};
#pragma pack(pop)
