//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHL2MPRules.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CHL2MPRules
	{
	public:
		unsigned char _0x0[0x20];
		int    	m_bTeamPlayEnabled; // 0x20
	};
#pragma pack(pop)
