//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CHLSelectFireMachineGun.h
//***********************************************

#pragma once

#include "CHLMachineGun.h"

#pragma pack(push,1)
	class CHLSelectFireMachineGun : 
		 public CHLMachineGun // 0x0
	{
	public:
	};
#pragma pack(pop)
