//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CInfoLightingRelative.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CInfoLightingRelative : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_hLightingLandmark; // 0x1388
	};
#pragma pack(pop)
