//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CInfoOverlayAccessor.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CInfoOverlayAccessor
	{
	public:
		unsigned char _0x0[0x4cc];
		int    	m_iTextureFrameIndex; // 0x4cc
		unsigned char _0x4d0[0xeb8];
		int    	m_iOverlayID; // 0x1388
	};
#pragma pack(pop)
