//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CInfoTeleporterCountdown.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CInfoTeleporterCountdown : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_bCountdownStarted; // 0x1388
		int    	m_bDisabled; // 0x1389
		float  	m_flStartTime; // 0x138c
		float  	m_flTimeRemaining; // 0x1390
	};
#pragma pack(pop)
