//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CLocalWeaponData.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CLocalWeaponData
	{
	public:
		unsigned char _0x0[0x17c8];
		int    	m_nViewModelIndex; // 0x17c8
		unsigned char _0x17cc[0x3c];
		int    	m_iPrimaryAmmoType; // 0x1808
		int    	m_iSecondaryAmmoType; // 0x180c
		int    	m_iClip1; // 0x1810
		int    	m_iClip2; // 0x1814
		unsigned char _0x1818[0x28];
		int    	m_bFlipViewModel; // 0x1840
	};
#pragma pack(pop)
