//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CLuaNextBot.h
//***********************************************

#pragma once

#include "CNextBot.h"
#include "CScriptedEntity.h"

#pragma pack(push,1)
	class CLuaNextBot : 
		 public CNextBot // 0x0
	{
	public:
		unsigned char _0x0[0x2230];
		CScriptedEntity	m_ScriptedEntity; // 0x2230
	};
#pragma pack(pop)
