//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CMaterialModifyControl.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CMaterialModifyControl : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		char*  	m_szMaterialName; // 0x1388
		unsigned char _0x138c[0xfb];
		char*  	m_szMaterialVar; // 0x1487
		unsigned char _0x148b[0xfb];
		char*  	m_szMaterialVarValue; // 0x1586
		unsigned char _0x158a[0x106];
		int    	m_iFrameStart; // 0x1690
		int    	m_iFrameEnd; // 0x1694
		int    	m_bWrap; // 0x1698
		float  	m_flFramerate; // 0x169c
		int    	m_bNewAnimCommandsSemaphore; // 0x16a0
		float  	m_flFloatLerpStartValue; // 0x16a4
		float  	m_flFloatLerpEndValue; // 0x16a8
		float  	m_flFloatLerpTransitionTime; // 0x16ac
		int    	m_bFloatLerpWrap; // 0x16b0
		unsigned char _0x16b4[0x4];
		int    	m_nModifyMode; // 0x16b8
	};
#pragma pack(pop)
