//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CMortarShell.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CMortarShell : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x54];
		float  	m_flLifespan; // 0x1394
		float  	m_flRadius; // 0x1398
		unsigned char _0x139c[0x4];
		vector3	m_vecSurfaceNormal; // 0x13a0
	};
#pragma pack(pop)
