//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CMovieExplosion.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CMovieExplosion : 
		 public CBaseParticleEntity // 0x0
	{
	public:
	};
#pragma pack(pop)
