//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CNPC_Strider.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CNPC_Strider : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x58];
		vector3	m_vecHitPos; // 0x2284
		vector3	m_vecIKTarget_0; // 0x2290
		vector3	m_vecIKTarget_1; // 0x229c
		vector3	m_vecIKTarget_2; // 0x22a8
		vector3	m_vecIKTarget_3; // 0x22b4
		vector3	m_vecIKTarget_4; // 0x22c0
		vector3	m_vecIKTarget_5; // 0x22cc
	};
#pragma pack(pop)
