//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CNPC_Manhack.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CNPC_Manhack : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x10];
		int    	m_nEnginePitch1; // 0x223c
		int    	m_nEnginePitch2; // 0x2240
		float  	m_flEnginePitch1Time; // 0x2244
		float  	m_flEnginePitch2Time; // 0x2248
	};
#pragma pack(pop)
