//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CNPC_Barney.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CNPC_Barney : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
	};
#pragma pack(pop)
