//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CNPC_AntlionGuard.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CNPC_AntlionGuard : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x4];
		int    	m_bCavernBreed; // 0x2230
		int    	m_bInCavern; // 0x2231
		unsigned char _0x2235[0x3];
		int    	m_iBleedingLevel; // 0x2238
	};
#pragma pack(pop)
