//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CNPC_Vortigaunt.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CNPC_Vortigaunt
	{
	public:
		unsigned char _0x0[0x2230];
		int    	m_bIsBlue; // 0x2230
		float  	m_flBlueEndFadeTime; // 0x2234
		int    	m_bIsBlack; // 0x2238
	};
#pragma pack(pop)
