//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CNPC_Puppet.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CNPC_Puppet : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x4];
		int    	m_hAnimationTarget; // 0x2230
		int    	m_nTargetAttachment; // 0x2234
	};
#pragma pack(pop)
