//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: COverlayVars.h
//***********************************************

#pragma once

#include "_ST_m_AnimOverlay_15.h"

#pragma pack(push,1)
	class COverlayVars
	{
	public:
		_ST_m_AnimOverlay_15	m_AnimOverlay; // 0x0
	};
#pragma pack(pop)
