//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CParticlePerformanceMonitor.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CParticlePerformanceMonitor : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_bDisplayPerf; // 0x1388
		int    	m_bMeasurePerf; // 0x1389
	};
#pragma pack(pop)
