//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CParticleSmokeGrenade.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CParticleSmokeGrenade : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1474];
		int    	m_CurrentStage; // 0x1474
		unsigned char _0x1478[0xc];
		float  	m_flSpawnTime; // 0x1484
		float  	m_FadeStartTime; // 0x1488
		float  	m_FadeEndTime; // 0x148c
	};
#pragma pack(pop)
