//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CParticleFire.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CParticleFire
	{
	public:
		unsigned char _0x0[0x147c];
		vector3	m_vOrigin; // 0x147c
		vector3	m_vDirection; // 0x1488
	};
#pragma pack(pop)
