//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPhysicsPropMultiplayer.h
//***********************************************

#pragma once

#include "CPhysicsProp.h"

#pragma pack(push,1)
	class CPhysicsPropMultiplayer : 
		 public CPhysicsProp // 0x17c4
	{
	public:
		unsigned char _0x17c4[0x8];
		int    	m_iPhysicsMode; // 0x17cc
		float  	m_fMass; // 0x17d0
		vector3	m_collisionMins; // 0x17d4
		vector3	m_collisionMaxs; // 0x17e0
	};
#pragma pack(pop)
