//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPhysBeam.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CPhysBeam : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x58];
		int    	m_iPhysBone; // 0x1398
		vector3	m_HoldPos; // 0x139c
		int    	m_hTargetEnt; // 0x13a8
		int    	m_bIsOn; // 0x13ac
	};
#pragma pack(pop)
