//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPhysBoxMultiplayer.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CPhysBoxMultiplayer
	{
	public:
		unsigned char _0x0[0x1394];
		int    	m_iPhysicsMode; // 0x1394
		float  	m_fMass; // 0x1398
	};
#pragma pack(pop)
