//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPlayerState.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CPlayerState
	{
	public:
		unsigned char _0x0[0x4];
		int    	deadflag; // 0x4
	};
#pragma pack(pop)
