//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPlasmaBeamNode.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CPlasmaBeamNode : 
		 public CBaseEntity // 0x1340
	{
	public:
		vector3	m_vecVelocity; // 0xf4
		unsigned char _0x100[0x1288];
		int    	m_bSprayOn; // 0x1388
	};
#pragma pack(pop)
