//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPointCamera.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CPointCamera : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_FOV; // 0x1388
		float  	m_Resolution; // 0x138c
		int    	m_bFogEnable; // 0x1390
		int    	m_FogColor; // 0x1391
		unsigned char _0x1395[0x3];
		float  	m_flFogStart; // 0x1398
		float  	m_flFogEnd; // 0x139c
		float  	m_flFogMaxDensity; // 0x13a0
		int    	m_bActive; // 0x13a4
		int    	m_bUseScreenAspectRatio; // 0x13a5
		int    	m_bGlobalOverride; // 0x13a6
	};
#pragma pack(pop)
