//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPredictedViewModel.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CPredictedViewModel
	{
	public:
	};
#pragma pack(pop)
