//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPredictableId.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CPredictableId
	{
	public:
		unsigned char _0x0[0xa0];
		int    	m_PredictableID; // 0xa0
		unsigned char _0xa4[0x424];
		int    	m_bIsPlayerSimulated; // 0x4c8
	};
#pragma pack(pop)
