//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPrecipitation.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CPrecipitation : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x70];
		int    	m_nPrecipType; // 0x13b0
	};
#pragma pack(pop)
