//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPropCombineBall.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CPropCombineBall : 
		 public CBaseAnimating // 0x1778
	{
	public:
		unsigned char _0x1778[0x54];
		int    	m_bEmit; // 0x17cc
		float  	m_flRadius; // 0x17d0
		int    	m_bHeld; // 0x17d4
		int    	m_bLaunched; // 0x17d5
	};
#pragma pack(pop)
