//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPropVehiclePrisonerPod.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CPropVehiclePrisonerPod
	{
	public:
		unsigned char _0x0[0x17cc];
		int    	m_hPlayer; // 0x17cc
		unsigned char _0x17d0[0x4];
		int    	m_bEnterAnimOn; // 0x17d4
		int    	m_bExitAnimOn; // 0x17d5
		int    	m_bLimitView; // 0x17d6
		vector3	m_vecEyeExitEndpoint; // 0x17d8
	};
#pragma pack(pop)
