//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPropJeep.h
//***********************************************

#pragma once

#include "CPropVehicleDriveable.h"

#pragma pack(push,1)
	class CPropJeep : 
		 public CPropVehicleDriveable // 0x1855
	{
	public:
		unsigned char _0x1855[0xb7];
		int    	m_bHeadlightIsOn; // 0x190c
	};
#pragma pack(pop)
