//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPropAirboat.h
//***********************************************

#pragma once

#include "CPropVehicleDriveable.h"

#pragma pack(push,1)
	class CPropAirboat : 
		 public CPropVehicleDriveable // 0x1855
	{
	public:
		int    	m_nWaterLevel; // 0x17c
		unsigned char _0x180[0x1784];
		int    	m_bHeadlightIsOn; // 0x1904
		int    	m_nAmmoCount; // 0x1908
		unsigned char _0x190c[0x4];
		int    	m_nExactWaterLevel; // 0x1910
		unsigned char _0x1914[0x37c];
		vector3	m_vecPhysVelocity; // 0x1c90
	};
#pragma pack(pop)
