//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CPropVehicleDriveable.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CPropVehicleDriveable : 
		 public CBaseAnimating // 0x1778
	{
	public:
		unsigned char _0x1778[0x4c];
		int    	m_hPlayer; // 0x17c4
		int    	m_nSpeed; // 0x17c8
		int    	m_nRPM; // 0x17cc
		float  	m_flThrottle; // 0x17d0
		int    	m_nBoostTimeLeft; // 0x17d4
		int    	m_nHasBoost; // 0x17d8
		int    	m_nScannerDisabledWeapons; // 0x17dc
		int    	m_nScannerDisabledVehicle; // 0x17e0
		unsigned char _0x17e4[0x1c];
		int    	m_bEnterAnimOn; // 0x1800
		int    	m_bExitAnimOn; // 0x1801
		unsigned char _0x1805[0x3];
		vector3	m_vecGunCrosshair; // 0x1808
		unsigned char _0x1814[0x30];
		vector3	m_vecEyeExitEndpoint; // 0x1844
		int    	m_bHasGun; // 0x1850
		int    	m_bUnableToFire; // 0x1851
	};
#pragma pack(pop)
