//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CProxyToggle_ProxiedData.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CProxyToggle_ProxiedData
	{
	public:
		unsigned char _0x0[0x1388];
		int    	m_WithProxy; // 0x1388
	};
#pragma pack(pop)
