//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CQuadraticBeam.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CQuadraticBeam : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		vector3	m_targetPosition; // 0x1388
		vector3	m_controlPosition; // 0x1394
		float  	m_scrollRate; // 0x13a0
		float  	m_flWidth; // 0x13a4
	};
#pragma pack(pop)
