//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CRagdollManager.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CRagdollManager
	{
	public:
		unsigned char _0x0[0x1388];
		int    	m_iCurrentMaxRagdollCount; // 0x1388
	};
#pragma pack(pop)
