//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CRagdoll.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CRagdoll : 
		 public CBaseAnimating // 0x1778
	{
	public:
		unsigned char _0x1778[0x48];
		vector3	m_ragPos_ 0 ; // 0x17c0
		vector3	m_ragPos_ 1 ; // 0x17cc
		vector3	m_ragPos_ 2 ; // 0x17d8
		vector3	m_ragPos_ 3 ; // 0x17e4
		vector3	m_ragPos_ 4 ; // 0x17f0
		vector3	m_ragPos_ 5 ; // 0x17fc
		vector3	m_ragPos_ 6 ; // 0x1808
		vector3	m_ragPos_ 7 ; // 0x1814
		vector3	m_ragPos_ 8 ; // 0x1820
		vector3	m_ragPos_ 9 ; // 0x182c
		vector3	m_ragPos_ 10 ; // 0x1838
		vector3	m_ragPos_ 11 ; // 0x1844
		vector3	m_ragPos_ 12 ; // 0x1850
		vector3	m_ragPos_ 13 ; // 0x185c
		vector3	m_ragPos_ 14 ; // 0x1868
		vector3	m_ragPos_ 15 ; // 0x1874
		vector3	m_ragPos_ 16 ; // 0x1880
		vector3	m_ragPos_ 17 ; // 0x188c
		vector3	m_ragPos_ 18 ; // 0x1898
		vector3	m_ragPos_ 19 ; // 0x18a4
		vector3	m_ragPos_ 20 ; // 0x18b0
		vector3	m_ragPos_ 21 ; // 0x18bc
		vector3	m_ragPos_ 22 ; // 0x18c8
		vector3	m_ragPos_ 23 ; // 0x18d4
		vector3	m_ragPos_ 24 ; // 0x18e0
		vector3	m_ragPos_ 25 ; // 0x18ec
		vector3	m_ragPos_ 26 ; // 0x18f8
		vector3	m_ragPos_ 27 ; // 0x1904
		vector3	m_ragPos_ 28 ; // 0x1910
		vector3	m_ragPos_ 29 ; // 0x191c
		vector3	m_ragPos_ 30 ; // 0x1928
		vector3	m_ragPos_ 31 ; // 0x1934
		vector3	m_ragAngles_ 0 ; // 0x1940
		vector3	m_ragAngles_ 1 ; // 0x194c
		vector3	m_ragAngles_ 2 ; // 0x1958
		vector3	m_ragAngles_ 3 ; // 0x1964
		vector3	m_ragAngles_ 4 ; // 0x1970
		vector3	m_ragAngles_ 5 ; // 0x197c
		vector3	m_ragAngles_ 6 ; // 0x1988
		vector3	m_ragAngles_ 7 ; // 0x1994
		vector3	m_ragAngles_ 8 ; // 0x19a0
		vector3	m_ragAngles_ 9 ; // 0x19ac
		vector3	m_ragAngles_ 10 ; // 0x19b8
		vector3	m_ragAngles_ 11 ; // 0x19c4
		vector3	m_ragAngles_ 12 ; // 0x19d0
		vector3	m_ragAngles_ 13 ; // 0x19dc
		vector3	m_ragAngles_ 14 ; // 0x19e8
		vector3	m_ragAngles_ 15 ; // 0x19f4
		vector3	m_ragAngles_ 16 ; // 0x1a00
		vector3	m_ragAngles_ 17 ; // 0x1a0c
		vector3	m_ragAngles_ 18 ; // 0x1a18
		vector3	m_ragAngles_ 19 ; // 0x1a24
		vector3	m_ragAngles_ 20 ; // 0x1a30
		vector3	m_ragAngles_ 21 ; // 0x1a3c
		vector3	m_ragAngles_ 22 ; // 0x1a48
		vector3	m_ragAngles_ 23 ; // 0x1a54
		vector3	m_ragAngles_ 24 ; // 0x1a60
		vector3	m_ragAngles_ 25 ; // 0x1a6c
		vector3	m_ragAngles_ 26 ; // 0x1a78
		vector3	m_ragAngles_ 27 ; // 0x1a84
		vector3	m_ragAngles_ 28 ; // 0x1a90
		vector3	m_ragAngles_ 29 ; // 0x1a9c
		vector3	m_ragAngles_ 30 ; // 0x1aa8
		vector3	m_ragAngles_ 31 ; // 0x1ab4
		unsigned char _0x1ac0[0xe8];
		int    	m_hUnragdoll; // 0x1ba8
		float  	m_flBlendWeight; // 0x1bac
		unsigned char _0x1bb0[0x4];
		int    	m_nOverlaySequence; // 0x1bb4
	};
#pragma pack(pop)
