//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CRagdoll_Attached.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CRagdoll_Attached
	{
	public:
		unsigned char _0x0[0x1bc0];
		vector3	m_attachmentPointBoneSpace; // 0x1bc0
		unsigned char _0x1bcc[0xc];
		vector3	m_attachmentPointRagdollSpace; // 0x1bd8
		int    	m_ragdollAttachedObjectIndex; // 0x1be4
		int    	m_boneIndexAttached; // 0x1be8
	};
#pragma pack(pop)
