//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CRocketTrail.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CRocketTrail : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1474];
		float  	m_SpawnRate; // 0x1474
		vector3	m_StartColor; // 0x1478
		vector3	m_EndColor; // 0x1484
		float  	m_Opacity; // 0x1490
		float  	m_ParticleLifetime; // 0x1494
		float  	m_StopEmitTime; // 0x1498
		float  	m_MinSpeed; // 0x149c
		float  	m_MaxSpeed; // 0x14a0
		float  	m_StartSize; // 0x14a4
		float  	m_EndSize; // 0x14a8
		float  	m_SpawnRadius; // 0x14ac
		unsigned char _0x14b0[0xc];
		int    	m_bEmit; // 0x14bc
		int    	m_bDamaged; // 0x14bd
		int    	m_nAttachment; // 0x14c0
		unsigned char _0x14c4[0xc];
		float  	m_flFlareScale; // 0x14d0
	};
#pragma pack(pop)
