//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CRollerMine.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"

#pragma pack(push,1)
	class CRollerMine : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x4];
		int    	m_bIsOpen; // 0x2230
		float  	m_flActiveTime; // 0x2234
		int    	m_bHackedByAlyx; // 0x2238
		int    	m_bPowerDown; // 0x2239
	};
#pragma pack(pop)
