//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CRotorWashEmitter.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CRotorWashEmitter : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flAltitude; // 0x1388
	};
#pragma pack(pop)
