//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSceneEntity.h
//***********************************************

#pragma once

#include "CBaseEntity.h"
#include "_ST_m_hActorList_16.h"

#pragma pack(push,1)
	class CSceneEntity : 
		 public CBaseEntity // 0x1340
	{
	public:
		_ST_m_hActorList_16	m_hActorList; // 0x0
		unsigned char _0x4[0x1388];
		int    	m_bIsPlayingBack; // 0x138c
		int    	m_bPaused; // 0x138d
		int    	m_bMultiplayer; // 0x138e
		unsigned char _0x1392[0x2];
		float  	m_flForceClientTime; // 0x1394
		int    	m_nSceneStringIndex; // 0x1398
	};
#pragma pack(pop)
