//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CScriptedEntity.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CScriptedEntity
	{
	public:
		unsigned char _0x0[0x10];
		char*  	m_strScriptName; // 0x10
	};
#pragma pack(pop)
