//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSENT_AI.h
//***********************************************

#pragma once

#include "CAI_BaseNPC.h"
#include "CScriptedEntity.h"

#pragma pack(push,1)
	class CSENT_AI : 
		 public CAI_BaseNPC // 0x222c
	{
	public:
		unsigned char _0x222c[0x4];
		CScriptedEntity	m_ScriptedEntity; // 0x2230
	};
#pragma pack(pop)
