//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSENT_anim.h
//***********************************************

#pragma once

#include "CBaseAnimatingOverlay.h"
#include "CScriptedEntity.h"

#pragma pack(push,1)
	class CSENT_anim : 
		 public CBaseAnimatingOverlay // 0x18
	{
	public:
		unsigned char _0x18[0x1814];
		CScriptedEntity	m_ScriptedEntity; // 0x182c
	};
#pragma pack(pop)
