//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSENT_point.h
//***********************************************

#pragma once

#include "CBaseEntity.h"
#include "CScriptedEntity.h"

#pragma pack(push,1)
	class CSENT_point : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		CScriptedEntity	m_ScriptedEntity; // 0x1388
	};
#pragma pack(pop)
