//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CServerAnimationData.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CServerAnimationData
	{
	public:
		unsigned char _0x0[0x1638];
		float  	m_flCycle; // 0x1638
	};
#pragma pack(pop)
