//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSlideshowDisplay.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CSlideshowDisplay : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		int    	m_bEnabled; // 0x1388
		char*  	m_szDisplayText; // 0x1389
		unsigned char _0x138d[0x7c];
		char*  	m_szSlideshowDirectory; // 0x1409
		unsigned char _0x140d[0x93];
		bool   	m_chCurrentSlideLists[16]; // 0x14a0
		unsigned char _0x14b0[0x8];
		float  	m_fMinSlideTime; // 0x14b8
		float  	m_fMaxSlideTime; // 0x14bc
		unsigned char _0x14c0[0x4];
		int    	m_iCycleType; // 0x14c4
		int    	m_bNoListRepeats; // 0x14c8
	};
#pragma pack(pop)
