//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSporeExplosion.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CSporeExplosion : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1474];
		float  	m_flSpawnRate; // 0x1474
		float  	m_flParticleLifetime; // 0x1478
		float  	m_flStartSize; // 0x147c
		float  	m_flEndSize; // 0x1480
		float  	m_flSpawnRadius; // 0x1484
		unsigned char _0x1488[0x4];
		int    	m_bEmit; // 0x148c
		int    	m_bDontRemove; // 0x148d
	};
#pragma pack(pop)
