//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSporeTrail.h
//***********************************************

#pragma once

#include "CBaseParticleEntity.h"

#pragma pack(push,1)
	class CSporeTrail : 
		 public CBaseParticleEntity // 0x0
	{
	public:
		unsigned char _0x0[0x1470];
		vector3	m_vecEndColor; // 0x1470
		float  	m_flSpawnRate; // 0x147c
		float  	m_flParticleLifetime; // 0x1480
		float  	m_flStartSize; // 0x1484
		float  	m_flEndSize; // 0x1488
		float  	m_flSpawnRadius; // 0x148c
		unsigned char _0x1490[0xc];
		int    	m_bEmit; // 0x149c
	};
#pragma pack(pop)
