//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSpriteOriented.h
//***********************************************

#pragma once

#include "CSprite.h"

#pragma pack(push,1)
	class CSpriteOriented : 
		 public CSprite // 0x13c8
	{
	public:
	};
#pragma pack(pop)
