//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CSprite.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CSprite : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x58];
		int    	m_hAttachedToEntity; // 0x1398
		int    	m_nAttachment; // 0x139c
		float  	m_flSpriteFramerate; // 0x13a0
		float  	m_flFrame; // 0x13a4
		unsigned char _0x13a8[0x4];
		int    	m_nBrightness; // 0x13ac
		float  	m_flBrightnessTime; // 0x13b0
		float  	m_flSpriteScale; // 0x13b4
		float  	m_flScaleTime; // 0x13b8
		int    	m_bWorldSpaceScale; // 0x13bc
		float  	m_flGlowProxySize; // 0x13c0
		float  	m_flHDRColorScale; // 0x13c4
	};
#pragma pack(pop)
