//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEArmorRicochet.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEArmorRicochet
	{
	public:
	};
#pragma pack(pop)
