//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEAntlionDust.h
//***********************************************

#pragma once

#include "CTEParticleSystem.h"

#pragma pack(push,1)
	class CTEAntlionDust : 
		 public CTEParticleSystem // 0x1c
	{
	public:
		unsigned char _0x1c[0x4];
		vector3	m_vecOrigin; // 0x20
		vector3	m_vecAngles; // 0x2c
		int    	m_bBlockedSpawner; // 0x38
	};
#pragma pack(pop)
