//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTeam.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTeam
	{
	public:
		int    	player_array_element; // 0x0
		unsigned char _0x4[0x1398];
		char*  	m_szTeamname; // 0x139c
		unsigned char _0x13a0[0x1c];
		int    	m_iScore; // 0x13bc
		int    	m_iRoundsWon; // 0x13c0
		unsigned char _0x13c4[0xc];
		int    	m_iTeamNum; // 0x13d0
	};
#pragma pack(pop)
