//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEBeamSpline.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEBeamSpline
	{
	public:
		bool   	m_vecPoints[1]; // 0x0
		unsigned char _0x0[0x10];
		vector3	m_vecPoints_0; // 0x10
		unsigned char _0x1c[0xb4];
		int    	m_nPoints; // 0xd0
	};
#pragma pack(pop)
