//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEBeamRingPoint.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEBeamRingPoint
	{
	public:
		unsigned char _0x0[0x4c];
		vector3	m_vecCenter; // 0x4c
		float  	m_flStartRadius; // 0x58
		float  	m_flEndRadius; // 0x5c
	};
#pragma pack(pop)
