//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEBeamFollow.h
//***********************************************

#pragma once

#include "CBaseBeam.h"

#pragma pack(push,1)
	class CTEBeamFollow : 
		 public CBaseBeam // 0x4c
	{
	public:
		int    	m_iEntIndex; // 0x4c
	};
#pragma pack(pop)
