//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEConcussiveExplosion.h
//***********************************************

#pragma once

#include "CTEParticleSystem.h"

#pragma pack(push,1)
	class CTEConcussiveExplosion : 
		 public CTEParticleSystem // 0x1c
	{
	public:
		vector3	m_vecNormal; // 0x1c
		float  	m_flScale; // 0x28
		int    	m_nRadius; // 0x2c
		int    	m_nMagnitude; // 0x30
	};
#pragma pack(pop)
