//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEEnergySplash.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEEnergySplash
	{
	public:
		unsigned char _0x0[0x10];
		vector3	m_vecPos; // 0x10
		vector3	m_vecDir; // 0x1c
		int    	m_bExplosive; // 0x28
	};
#pragma pack(pop)
