//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEMetalSparks.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEMetalSparks
	{
	public:
		unsigned char _0x0[0x10];
		vector3	m_vecPos; // 0x10
		vector3	m_vecDir; // 0x1c
	};
#pragma pack(pop)
