//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEPlayerAnimEvent.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEPlayerAnimEvent
	{
	public:
		unsigned char _0x0[0x10];
		int    	m_hPlayer; // 0x10
		int    	m_iEvent; // 0x14
		int    	m_nData; // 0x18
	};
#pragma pack(pop)
