//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEParticleSystem.h
//***********************************************

#pragma once

#include "CBaseTempEntity.h"

#pragma pack(push,1)
	class CTEParticleSystem : 
		 public CBaseTempEntity // 0x0
	{
	public:
		unsigned char _0x0[0x10];
		float  	m_vecOrigin_0; // 0x10
		float  	m_vecOrigin_1; // 0x14
		float  	m_vecOrigin_2; // 0x18
	};
#pragma pack(pop)
