//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEShowLine.h
//***********************************************

#pragma once

#include "CTEParticleSystem.h"

#pragma pack(push,1)
	class CTEShowLine : 
		 public CTEParticleSystem // 0x1c
	{
	public:
		vector3	m_vecEnd; // 0x1c
	};
#pragma pack(pop)
