//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTestTraceline.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTestTraceline
	{
	public:
		unsigned char _0x0[0x58];
		int    	m_clrRender; // 0x58
		unsigned char _0x5c[0x134];
		int    	moveparent; // 0x190
		unsigned char _0x194[0x1a4];
		vector3	m_vecOrigin; // 0x338
		float  	m_angRotation_0; // 0x344
		float  	m_angRotation_1; // 0x348
		float  	m_angRotation_2; // 0x34c
	};
#pragma pack(pop)
