//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTESparks.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTESparks
	{
	public:
		unsigned char _0x0[0x1c];
		int    	m_nMagnitude; // 0x1c
		int    	m_nTrailLength; // 0x20
		vector3	m_vecDir; // 0x24
	};
#pragma pack(pop)
