//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTesla.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CTesla : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x70];
		char*  	m_SoundName; // 0x13b0
		unsigned char _0x13b4[0x3c];
		char*  	m_iszSpriteName; // 0x13f0
	};
#pragma pack(pop)
