//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CTEWorldDecal.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CTEWorldDecal
	{
	public:
		unsigned char _0x0[0x10];
		vector3	m_vecOrigin; // 0x10
		int    	m_nIndex; // 0x1c
	};
#pragma pack(pop)
