//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CVGuiScreen.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CVGuiScreen : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x50];
		float  	m_flWidth; // 0x1390
		float  	m_flHeight; // 0x1394
		int    	m_nPanelName; // 0x1398
		unsigned char _0x139c[0x18];
		int    	m_nAttachmentIndex; // 0x13b4
		int    	m_nOverlayMaterial; // 0x13b8
		int    	m_fScreenFlags; // 0x13bc
		unsigned char _0x13c0[0x58];
		int    	m_hPlayerOwner; // 0x1418
	};
#pragma pack(pop)
