//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CVortigauntChargeToken.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CVortigauntChargeToken : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x50];
		int    	m_bFadeOut; // 0x1390
	};
#pragma pack(pop)
