//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CVortigauntEffectDispel.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CVortigauntEffectDispel : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x54];
		int    	m_bFadeOut; // 0x1394
	};
#pragma pack(pop)
