//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CVoteController.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CVoteController : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x50];
		int    	m_iActiveIssueIndex; // 0x1390
		int    	m_iOnlyTeamToVote; // 0x1394
		int    	m_nVoteOptionCount[5]; // 0x1398
		unsigned char _0x13ac[0x4];
		int    	m_nPotentialVotes; // 0x13b0
		unsigned char _0x13b4[0x2];
		int    	m_bIsYesNoVote; // 0x13b6
	};
#pragma pack(pop)
