//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWaterBullet.h
//***********************************************

#pragma once

#include "CBaseAnimating.h"

#pragma pack(push,1)
	class CWaterBullet : 
		 public CBaseAnimating // 0x1778
	{
	public:
	};
#pragma pack(pop)
