//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWaterLODControl.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CWaterLODControl : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flCheapWaterStartDistance; // 0x1388
		float  	m_flCheapWaterEndDistance; // 0x138c
	};
#pragma pack(pop)
