//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponBinoculars.h
//***********************************************

#pragma once

#include "CBaseHLCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponBinoculars : 
		 public CBaseHLCombatWeapon // 0x0
	{
	public:
	};
#pragma pack(pop)
