//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponCrowbar.h
//***********************************************

#pragma once

#include "CBaseHL2MPBludgeonWeapon.h"

#pragma pack(push,1)
	class CWeaponCrowbar : 
		 public CBaseHL2MPBludgeonWeapon // 0x0
	{
	public:
	};
#pragma pack(pop)
