//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponFrag.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponFrag : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x1898];
		int    	m_bRedraw; // 0x1898
		int    	m_AttackPaused; // 0x189c
		int    	m_fDrawbackFinished; // 0x18a0
	};
#pragma pack(pop)
