//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponAR2.h
//***********************************************

#pragma once

#include "CHL2MPMachineGun.h"

#pragma pack(push,1)
	class CWeaponAR2 : 
		 public CHL2MPMachineGun // 0x189c
	{
	public:
	};
#pragma pack(pop)
