//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponHL2MPBase.h
//***********************************************

#pragma once

#include "CBaseCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponHL2MPBase : 
		 public CBaseCombatWeapon // 0x1804
	{
	public:
	};
#pragma pack(pop)
