//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponStunStick.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CWeaponStunStick
	{
	public:
		unsigned char _0x0[0x18ec];
		int    	m_bActive; // 0x18ec
	};
#pragma pack(pop)
