//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponSMG1.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CWeaponSMG1
	{
	public:
	};
#pragma pack(pop)
