//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponAlyxGun.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CWeaponAlyxGun
	{
	public:
	};
#pragma pack(pop)
