//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponPhysGun.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponPhysGun : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x1898];
		int    	m_hGrabbedEntity; // 0x1898
		int    	m_hPhysBeam; // 0x189c
		vector3	m_vHitPosLocal; // 0x18a0
	};
#pragma pack(pop)
