//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponOldManHarpoon.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CWeaponOldManHarpoon
	{
	public:
	};
#pragma pack(pop)
