//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeapon_SLAM.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeapon_SLAM : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x1898];
		int    	m_tSlamState; // 0x1898
		int    	m_bDetonatorArmed; // 0x189c
		int    	m_bNeedDetonatorDraw; // 0x189d
		int    	m_bNeedDetonatorHolster; // 0x189e
		int    	m_bNeedReload; // 0x189f
		int    	m_bClearReload; // 0x18a0
		int    	m_bThrowSatchel; // 0x18a1
		int    	m_bAttachSatchel; // 0x18a2
		int    	m_bAttachTripmine; // 0x18a3
	};
#pragma pack(pop)
