//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponCitizenSuitcase.h
//***********************************************

#pragma once

#include "CWeaponCitizenPackage.h"

#pragma pack(push,1)
	class CWeaponCitizenSuitcase : 
		 public CWeaponCitizenPackage // 0x0
	{
	public:
	};
#pragma pack(pop)
