//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponHopwire.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CWeaponHopwire
	{
	public:
	};
#pragma pack(pop)
