//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponRPG.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponRPG : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x18a4];
		int    	m_bInitialStateUpdate; // 0x18a4
		int    	m_bGuiding; // 0x18a5
		int    	m_bHideGuiding; // 0x18a6
		int    	m_hMissile; // 0x18a8
		vector3	m_vecLaserDot; // 0x18ac
	};
#pragma pack(pop)
