//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponCycler.h
//***********************************************

#pragma once

#include "CBaseCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponCycler : 
		 public CBaseCombatWeapon // 0x1844
	{
	public:
	};
#pragma pack(pop)
