//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponCrossbow.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponCrossbow : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x189c];
		int    	m_bInZoom; // 0x189c
		int    	m_bMustReload; // 0x189d
	};
#pragma pack(pop)
