//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponPistol.h
//***********************************************

#pragma once

#include "CHL2MPMachineGun.h"

#pragma pack(push,1)
	class CWeaponPistol : 
		 public CHL2MPMachineGun // 0x189c
	{
	public:
		unsigned char _0x189c[0x4];
		float  	m_flSoonestPrimaryAttack; // 0x18a0
		float  	m_flLastAttackTime; // 0x18a4
		float  	m_flAccuracyPenalty; // 0x18a8
		int    	m_nNumShotsFired; // 0x18ac
	};
#pragma pack(pop)
