//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeapon357.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeapon357 : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
	};
#pragma pack(pop)
