//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponHandGrenade.h
//***********************************************

#pragma once


#pragma pack(push,1)
	class CWeaponHandGrenade
	{
	public:
		unsigned char _0x0[0x1868];
		float  	m_flStartThrow; // 0x1868
		float  	m_flReleaseThrow; // 0x186c
	};
#pragma pack(pop)
