//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWeaponShotgun.h
//***********************************************

#pragma once

#include "CBaseHL2MPCombatWeapon.h"

#pragma pack(push,1)
	class CWeaponShotgun : 
		 public CBaseHL2MPCombatWeapon // 0x0
	{
	public:
		unsigned char _0x0[0x1898];
		int    	m_bNeedPump; // 0x1898
		int    	m_bDelayedFire1; // 0x1899
		int    	m_bDelayedFire2; // 0x189a
		int    	m_bDelayedReload; // 0x189b
	};
#pragma pack(pop)
