//***********************************************
// SDK Generated by ValveGen (written by Chod)
// File: CWorld.h
//***********************************************

#pragma once

#include "CBaseEntity.h"

#pragma pack(push,1)
	class CWorld : 
		 public CBaseEntity // 0x1340
	{
	public:
		unsigned char _0x1340[0x48];
		float  	m_flWaveHeight; // 0x1388
		vector3	m_WorldMins; // 0x138c
		vector3	m_WorldMaxs; // 0x1398
		int    	m_bStartDark; // 0x13a4
		float  	m_flMaxOccludeeArea; // 0x13a8
		float  	m_flMinOccluderArea; // 0x13ac
		float  	m_flMinPropScreenSpaceWidth; // 0x13b0
		float  	m_flMaxPropScreenSpaceWidth; // 0x13b4
		int    	m_bColdWorld; // 0x13b8
		char*  	m_iszDetailSpriteMaterial; // 0x13b9
	};
#pragma pack(pop)
